pg = PageDirectoryIterator(relation1)
    a = pg.GetNextDataPageId()
    print(a)
    Dphr = DataPageHoldRecordIterator(a, relation1)
    print(Dphr.GetNextRecord().values)
    print(Dphr.GetNextRecord().values)
    print(Dphr.GetNextRecord().values)
    b = pg.GetNextDataPageId()
    print(b)
    Dphr = DataPageHoldRecordIterator(b, relation1)
    print(Dphr.GetNextRecord().values)